# Generated by Django 5.2.5 on 2026-02-25 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_generator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CVGeneration',
        ),
    ]
