# Generated by Django 5.2.5 on 2025-08-14 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, null=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, choices=[('Technology', 'Tecnología'), ('Finance', 'Finanzas'), ('Healthcare', 'Salud'), ('Education', 'Educación'), ('Marketing', 'Marketing'), ('Retail', 'Retail'), ('Consulting', 'Consultoría'), ('Other', 'Otro')], max_length=100, null=True)),
                ('plan', models.CharField(choices=[('Free', 'Gratis'), ('Basic', 'Básico'), ('Premium', 'Premium')], default='Free', max_length=20)),
                ('newsletter', models.BooleanField(default=False)),
                ('terms', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
