# Generated by Django 5.2.5 on 2025-09-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='years_of_experience',
            field=models.CharField(blank=True, choices=[('0-1', 'Menos de 1 año'), ('1-3', '1-3 años'), ('3-5', '3-5 años'), ('5-10', '5-10 años'), ('10+', 'Más de 10 años')], max_length=10, null=True),
        ),
    ]
