# Generated by Django 5.2.5 on 2025-12-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='personal_website',
            field=models.URLField(blank=True, help_text='Sitio web personal o portafolio', max_length=255, null=True),
        ),
    ]
