# Generated by Django 5.2.5 on 2026-01-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userprofile_location_workexperience_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
