# Generated by Django 5.2.5 on 2026-01-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['skill_type', '-level', 'name']},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 'Principiante'), ('INTERMEDIATE', 'Intermedio'), ('ADVANCED', 'Avanzado'), ('EXPERT', 'Experto')], default='INTERMEDIATE', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('TECHNICAL', 'Technical'), ('SOFT', 'Soft')], default='TECHNICAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
