# Generated by Django 5.2.5 on 2026-01-25 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_skill_options_remove_skill_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, help_text='Ej: Project Manager, Lead Designer, Content Creator', max_length=255)),
                ('organization', models.CharField(blank=True, help_text='Cliente, Empresa o Institución', max_length=255)),
                ('category', models.CharField(choices=[('PROFESSIONAL', 'Profesional / Trabajo'), ('FREELANCE', 'Freelance / Cliente'), ('ACADEMIC', 'Académico / Tesis'), ('PERSONAL', 'Proyecto Personal'), ('VOLUNTEER', 'Voluntariado')], default='PROFESSIONAL', max_length=20)),
                ('description', models.TextField()),
                ('project_url', models.URLField(blank=True, help_text='Enlace principal (Web, Portfolio, Noticia)', null=True)),
                ('resource_url', models.URLField(blank=True, help_text='Enlace secundario (PDF, Video, Drive, GitHub)', null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='projects', to='accounts.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-end_date', '-start_date'],
            },
        ),
    ]
