# Generated by Django 5.2.5 on 2026-02-25 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tailoredcv',
            name='job_posting',
        ),
        migrations.RemoveField(
            model_name='tailoredcv',
            name='user',
        ),
        migrations.DeleteModel(
            name='JobPosting',
        ),
        migrations.DeleteModel(
            name='TailoredCV',
        ),
    ]
